# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              http://bootstrap-anchor.com
encoding:         UTF-8

# Custom vars
name:             Bootstrap Anchor
description:      The missing Bootstrap plugin for anchor support.
current_version:  0.0.2
repo:             https://github.com/unicorn-fail/bootstrap-anchor

download:
  source:         https://github.com/unicorn-fail/bootstrap-anchor/archive/v0.0.2.zip
  dist:           https://github.com/unicorn-fail/bootstrap-anchor/releases/download/v0.0.2/bootstrap-anchor-0.0.2-dist.zip
